### PR TITLE
Single comp dev

### PR DESCRIPTION
**Pull request by andreapiras**

### CODE REVIEW

**Comment by StevePole** [comment]
Could you screenshot?

**Comment by andreapiras** [comment]
singlepage
@StevePole

**Comment by StevePole** [comment]
Why does checkbox appear on both pages?  Was expecting to see more of a navigation on the first page, then the actual component when you click in.

**Comment by andreapiras** [comment]
> Why does checkbox appear on both pages? Was expecting to see more of a navigation on the first page, then the actual component when you click in.

To be honest I'm not at that stage yet. This PR is more about adding the route generated automatically and to create a individual page for each component. All the details about how the navigation shoul behave is still tbd and open to discussion

**Comment by StevePole** [comment]
Ok, I think it's fine to do it incrementally, but I may avoid including the links to the new routes until we're ready.  So the components will be available on the main page, or on a route.  In a follow up we add navigation, and remove the docs from the main page?

**Comment by andreapiras** [comment]
Sure the link can be removed and leave the route available. I'm working on a another branch where I'm actually adding a sidebar and trying to set up a nice navigation. This PR is more of a show case where we can evaluate the code to achieve this setup

**Pull request closed without merging**
