### PR TITLE
Spinner component

### PR DESCRIPTION
**Pull request by jacklesliewise**
large

### CODE REVIEW

**Comment by StevePole** [comment]
Screenshot please :-)

**Comment by sergonius** [comment]
Perhaps something to consider is having a possibility to pass children to the spinner component.

Something like Ant has:
https://ant.design/components/spin/

Seems a common enough use-case and not a lot of extra work.

**Comment by domhorvathtw** [comment]
Could be just me, but isn't it weird in terms of naming, that there is **no spinning motion** in the animation of this component? If it's going to be used as a loading indicator, can we rename it to something like `<Loader />` `<LoadingIndicator />`?

We already have a `<Loader />` though, that's the one with the flag. 
And we also have a `<ProcessIndicator />`, which is used for multiple states (failed, succeeded), not just loading.  

Any thoughts?

**Comment by jacklesliewise** [comment]
Closing this in favour of #232

**Pull request closed without merging**
