### PR TITLE
Stop bundling flags

### PR DESCRIPTION
**Pull request by oliverviljamaa**
# v2.0.0
## Stops bundling currency flags

This makes the output CSS smaller and means we can avoid duplicating the flags CSS
if our app needs it in other places as well.

### CODE REVIEW

**Comment by oliverviljamaa** [comment]
Good point, @Tankenstein. Also, are you fine with the fact that it’s a major bump?

**Comment by oliverviljamaa** [comment]
@Tankenstein Added to `devDependencies` and made sure it works in the docs.

**Comment by Tankenstein** [comment]
Yep this is backwards incompatible.

**Comment by oliverviljamaa** [comment]
@Tankenstein The file size difference is as follows:

**Before:**: 39.87 kB
**After:** 1.23 kB

**Comment by Tankenstein** [comment]
@oliverviljamaa wait, seriously?

**Comment by Tankenstein** [comment]
fuckin' a man

**Pull request merged**
