### PR TITLE
Adds inverse state to FlowNavigation

### PR DESCRIPTION
**Pull request by williambaumgartner**
* Adds dark mode for FlowNavigation
* Adds new property `inverse` which shows the dark version
* Properly hides the border when `done` is `true` in FlowNavigation
* Adds `classnames` dev-dependency for easy class management
* Minor less refactoring

image

### CODE REVIEW

**Comment by StevePole** [comment]
Ok, makes sense, but this is an open source project, it doesn't know anything about the batch flow and whether there will/won't be steps.  I would say if you're going to add the feature, you should make it work for all cases.

Would be great to see the designs for this flow if they're kicking around somewhere?

**Comment by czebe** [comment]
You don't even need a FlowNavigation here, just a logo and a close button.

**Comment by williambaumgartner** [comment]
@StevePole Makes sense. Will ask for designs and update accordingly.

**Comment by williambaumgartner** [comment]
Closing this as I'll replicate the inverse done state.

**Pull request closed without merging**
